version: '3.8'

services:
  kobe:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"  # MLflow UI
    environment:
      - PYTHONPATH=/app
    command: tail -f /dev/null  # Mantém o container rodando

  jupyter:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8888:8888"  # Jupyter Notebook
    environment:
      - PYTHONPATH=/app
    command: kedro jupyter lab --no-browser --ip 0.0.0.0 --port 8888 --allow-root

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 